# Site settings
title: " | Nathan M"  # title will be called and appended to each subtitle
subtitle: "Home"  # page specific title variables will be called at a lower scope, overriding this variable
email: nathan.ed.mcdonald@outlook.com # TODO update email address
description: "My hub for all things computer science"
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site # TODO
author: "Nathan McDonald" # TODO redirect to github
street_address:
city: "Round Rock"
state: "TX"
zip_code: #
country: United States of America
phone: (817) 213-6283

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
