# Site settings
title: "Home"  # page specific title variables will be called at a lower scope
subtitle: " | Nathan M"  # subtitle will be called and appended after each title
email: youremailaddress@gmail.com # TODO update email address
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site # TODO
author: # TODO
street_address: 1234 Somewhere Road # TODO
city: Nashville # TODO
state: TN # TODO
zip_code: 55555 # TODO
country: United States of America # TODO
phone: (716) 555-5555 # TODO

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
