# Site settings
title: " | Nathan M"  # title will be called and appended to each subtitle
subtitle: "Home"  # page specific title variables will be called at a lower scope, overriding this variable
email: nathan.ed.mcdonald@outlook.com # TODO update email address
description: "My hub for all things computer science"
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site # TODO
author: "Nathan McDonald" # TODO redirect to github
street_address:
city: "Round Rock"
state: "TX"
zip_code: #
country: United States of America
phone: (817) 213-6283

# Icons and Links for compliance with licenses
python_svg: "assets/icons/python.svg"
python_url: "https://python.org"
numpy_svg: "assets/icons/numpy.svg"
numpy_url: https://numpy.org
github_svg: "assets/icons/github.svg"
github_url: https://github.com/stolenpromises/  # TODO update github user name
spyder_svg: "assets/icons/spyder.svg"
spyder_url: https://www.spyder-ide.org

#project images
robot_jpg: "assets/images/robot.jpg"
virus_jpg: "assets/images/virus.jpg"
this_website_jpg: "assets/images/website.svg"

# Social settings
500px_url:
facebook_url: https://www.facebook.com/therealnathan
gitlab_url:
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/nathanedmcdonald
pinterest_url:
slack_url:
twitter_url: https://twitter.com/therealnatemcd

# Build settings
markdown: kramdown

collections:
  - projects
  